language: node_js
node_js:
  - "node"

script: 'true'

env:
  CI: false
  
after_success:
  - git config --global user.name "NuwanJ"
  - git config --global user.email "nuwanjaliyagoda@gmail.com"
  - git remote rm origin
  - git remote add origin https://NuwanJ:f72174ed80dbbe2ae035715916a1bc5edad16845@github.com/NuwanJ/CO328-Project-Frontend-.git
  - npm run deploy
  
  
 
